[package]
name = "cncurses"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
dyn-clone = "1.0.19"
ncurses = "6.0.1"
once_cell = "1.21.3"

[profile.test]
test-threads = 1
